#!/bin/bash

if [ "true" = "$is_server" ];then
    kcp="./server_linux_amd64"
    sslocal -c ss.json -d start -s 127.0.0.1
else
    kcp="./client_linux_amd64"
    ssserver -c ss.json -d start
fi

$kcp -c kcp_ss.json

