#!/bin/bash

if [ "true" = "$is_server" ];then
    ssserver -c ss.json -d start
    ./server_linux_amd64 -c kcp_ss.json
else
    sslocal -c ss.json -d start
    ./client_linux_amd64 -c kcp_ss.json
fi


